name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: go-${{ matrix.go-version }}-${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.20"
          - "1.21"
          - "1.22"
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: make test
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"
      - uses: actions/checkout@v3
      - run: make format-check
